### ISSUE TITLE
Regex bug

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/DepEdit#47]
If I try to match a lemma with the constraint

`lemma=/Doctor|(Dr|Mrs?|Ms|Fr|Sr|St|Lt|Sgt|Pvt|G\.?I)\.?/`

it gives "TypeError: decoding to str: need a bytes-like object, NoneType found".

I guess there is some custom processing of the regex? Enclosing the whole contents in parentheses gets rid of the error.

**Comment by amir-zeldes** [comment]
No, I don't think it's a custom processing issue - the issue is that you must be using the capturing group in the replacement criterion, but strings matching "Doctor" will have no capturing group since that type of match in the disjunction is totally outside of any brackets. This means that if you're trying to set something to be identical to the lemma, but the matching lemma is "Doctor", then `$1` will be empty, so it will encounter None when it attempts to retrieve the value. I think crashing is actually a better behavior than doing something like using the empty string as the target value and not telling you about it, no?

**Comment by amir-zeldes** [comment]
I can add a warning explaining the issue, see 0a82f53
