### ISSUE TITLE
Fails for conllu ellipsis token with ID 10.1

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/DepEdit#7]
https://github.com/amir-zeldes/DepEdit/blob/710999ee739d644ecc6e935dbb1e3fa2c9b643f8/depedit/depedit.py#L780

A line that triggers the error:
https://github.com/UniversalDependencies/UD_English/blob/7b898d9ac599b3d21bc36f487234d75943081878/not-to-release/sources/answers/20111108072305AAPJTjj_ans.xml.conllu#L54

**Comment by amir-zeldes** [comment]
Yes, currently DepEdit does not support 'ellipsis' tokens, the assumptions is that all token IDs are integers. I'll need to check and see how difficult it is to support this. Maybe just cast to float? 

One consequence of this is that token distance definitions for rules like `#1.1,5#2` might be compromised (if you say 'within 5 tokens', does that include ellipsis tokens?). But in practice I suppose the main objective is just to make sure it doesn't crash due to these... Thanks for reporting!

**Comment by amir-zeldes** [comment]
It seems changing it to float basically works, though I'm rounding the ellipsis ID for distance checking purposes. But maybe that's actually desirable, if we have ID 10 and ID 11, we may want to say that they're adjacent, irrespective of ellipsis tokens (just a caveat). I'll commit a fix.
