### ISSUE TITLE
Basic dependency head of 0 is added for ellipsis node

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/DepEdit#9]
The ellipsis node should only exist in the enhanced representation, thus its basic dependency head column should be empty (`_`). E.g. for 20111108072305AAPJTjj_ans.xml.conllu:

```diff
54c54
< 10.1	has	have	VERB	VBZ	_	_	_	8:parataxis	CopyOf=-1
---
> 10.1	has	have	VERB	VBZ	_	0	_	8:parataxis	CopyOf=-1
```

**Comment by amir-zeldes** [comment]
I see, thanks. In the data model the assumption is that the head column is numeric, or else the tree is invalid (I think  some tools, like the current version of arborator/q.cgi might crash otherwise). But I guess it's easy to fix this for ellipsis tokens, which are a special case. I'm traveling the next couple of days but should get to it then.
